# WARNING: due to direct parsing by Bash script, this file should use an indentation of 2 spaces.

# Application settings used by various scripts.
app:
  container_name: myapp
  image_name: myapp
  image_version: latest
  run_service: myapp

# bin/build.bash parameters
build:
  clean: True
  base:
    image: python
    version: 3

# bin/sync.bash parameters
sync:
  user: myUsername
  host: example.com
  path: ~/srv/myApp/
