---

version: '3.1'

################################################################################

services:

################################################################################

    myapp:

        container_name: myapp
        image: myapp:latest
        restart: always

        build:
            context: ../
            dockerfile: "docker/${dockerFileBuild}"

        environment:

            PYTHONUNBUFFERED: 1

        command: /bin/bash

        volumes:
            - $APPPATH:/usr/src/app/:ro

################################################################################
