---

version: '3.1'

################################################################################

services:

################################################################################

    myapp:

        container_name: ${dockerContainerName}
        image: ${dockerBuildImage}:${dockerBuildVersion}

        restart: always                                     # For Server, or if X-11 Kiosk

        build:
            context: ${BASEPATH}
            dockerfile: docker/${dockerFileBuild}
            args:
                IMG_BASE: ${dockerImage}
                CODE_VERSION: ${dockerVersion}

        environment:

            PYTHONUNBUFFERED: 1
            # DISPLAY: ${DISPLAY}                           # Enable for X-11 support

        # volumes:
            # - "$HOME/.Xauthority:/root/.Xauthority:rw"    # Enable for X-11 support

################################################################################
