---

version: '3.1'

################################################################################

services:

################################################################################

    myapp:

        container_name: ${dockerContainerName}
        image: ${dockerBuildImage}:${dockerBuildVersion}
        restart: always

        build:
            context: ${BASEPATH}
            dockerfile: docker/${dockerFileBuild}
            args:
                IMG_BASE: ${dockerImage}
                CODE_VERSION: ${dockerVersion}

        environment:

            PYTHONUNBUFFERED: 1

################################################################################
